name: dave
dependencies:
- flask=1.0.3=py37_0
- jinja2=2.10.1=py37_0
- numpy=1.18.5=py37h1da2735_0
- llvmlite=0.33.0
- numba=0.50.1=py37h959d312_1
- pip=20.1.1=py37_1
- python=3.7.7
- werkzeug=0.14.1=py37_0
- pytest=5.4.3
- gevent=1.4.0
- pip:
  - astropy==3.2.1
  - requests==2.22.0
  - flask-session==0.3.2
  - hypothesis==5.20.2
  - python-magic==0.4.18
  - pylru==1.2.0
  - stingray
  - hendrics
  - python-libmagic
